In [2]:
import numpy as np
num = np.arange(72)
arr1 = np.reshape(num, [8, 9])
print("Original array:")
print(arr1)

Original array:
[[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16 17]
 [18 19 20 21 22 23 24 25 26]
 [27 28 29 30 31 32 33 34 35]
 [36 37 38 39 40 41 42 43 44]
 [45 46 47 48 49 50 51 52 53]
 [54 55 56 57 58 59 60 61 62]
 [63 64 65 66 67 68 69 70 71]]


In [23]:
arr2 = arr1[:7,:]
print(arr2)

[[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16 17]
 [18 19 20 21 22 23 24 25 26]
 [27 28 29 30 31 32 33 34 35]
 [36 37 38 39 40 41 42 43 44]
 [45 46 47 48 49 50 51 52 53]
 [54 55 56 57 58 59 60 61 62]]


In [24]:
print(arr2 * arr2)

[[   0    1    4    9   16   25   36   49   64]
 [  81  100  121  144  169  196  225  256  289]
 [ 324  361  400  441  484  529  576  625  676]
 [ 729  784  841  900  961 1024 1089 1156 1225]
 [1296 1369 1444 1521 1600 1681 1764 1849 1936]
 [2025 2116 2209 2304 2401 2500 2601 2704 2809]
 [2916 3025 3136 3249 3364 3481 3600 3721 3844]]


In [20]:
arr2=arr2.mean(axis=0)
print(arr2)

[27. 28. 29. 30. 31. 32. 33. 34. 35.]


In [21]:
arr3 = [i+1 for i in range(10)]
arr3 = np.asarray(arr3)
print(arr3)
print(arr3.sum())
print(np.sqrt(arr3.sum()))

[ 1  2  3  4  5  6  7  8  9 10]
55
7.416198487095663


In [11]:
arr4 = arr3[:9]
print(arr2)
print(arr4)

[189 196 203 210 217 224 231 238 245]
[1 2 3 4 5 6 7 8 9]


In [14]:
arr5 = arr2 * arr4
print(arr5)

[ 189  392  609  840 1085 1344 1617 1904 2205]


In [18]:
print(arr5[1:4])
print(arr5[1:4]/2)

[392 609 840]
[196.  304.5 420. ]
